import React, { useContext } from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { THEME } from '../components/Theme'
import ThemeContext from '../components/ThemeContext';

export default function Home() {
  const store = useContext(ThemeContext)


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome
        </h1>
        <button
          onClick={() =>
            store.changeTheme(
              store.theme === THEME.LIGHT ? THEME.DARK : THEME.LIGHT
            )
          }
        >
          {store.theme === THEME.LIGHT ? 'dark' : 'light'}
        </button>

      </main>

      <footer className={styles.footer}>

        <span className={styles.logo}>
          <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>

      </footer>
    </div>
  )
}